
driver:
  name: nfs.csi.k8s.io
  replicas: 1

storageClasses:
- name: nfs-csi
  defaultClass: false
  parameters:
    server: 192.168.50.94
    share: /mnt/k8s/
  mountOptions:
    - nfsvers=4.1

csiDriver:
  name: nfs.csi.k8s.io
  attachRequired: false
  fsGroupPolicy: File

kubeletDir: /var/lib/kubelet
