apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dify

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: dify
    repo: https://borispolonsky.github.io/dify-helm
    version: 0.27.0  # Check for latest version
    releaseName: dify
    namespace: dify
    valuesFile: values.yaml

labels:
  - pairs:
      app.kubernetes.io/name: dify
      app.kubernetes.io/managed-by: argocd