apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.25.0  # Check for latest version
    releaseName: vaultwarden
    namespace: vaultwarden
    valuesFile: values.yaml

labels:
  - pairs:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/managed-by: argocd